disabled_rules: # rule identifiers to exclude from running
  - blanket_disable_command
  - trailing_newline
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - class_delegate_protocol
opt_in_rules:
  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - WForecastUI/ProgressHUD
identifier_name:
  min_length: 2

